---
format: 
    docx:
        reference-doc: instructions/rmd-reference.docx
editor_options:
    markdown:
        wrap: 72
        canonical: true
---

# Research software engineer for a research-data infrastructure framework

The [Department of Clinical Medicine](https://clin.au.dk/) at [Faculty
of Health](https://health.au.dk/en/) at Aarhus University, in
collaboration with the [Steno Diabetes Center
Aarhus](https://www.stenoaarhus.dk/) (SDCA), invites applications for
one position as "research software engineer" to work (in person or
remote) with a team on a software and data infrastructure project,
starting March 1 or as soon as possible thereafter. This is a
fixed-term, full-time 2-year position.

At the Department of Clinical Medicine, you will be part of what is
probably the largest health science research department in Denmark. Our
clinical research covers all the medical specialties and takes place in
close collaboration with the university hospital and the regional
hospitals in the Central Denmark Region. At the department we are
approximately 425 academic employees and the same number of PhD students
cooperating across disciplines.

SDCA is a center that brings together researchers and clinicians in an
aim to better integrate work on multiple aspects of diabetes treatment,
research, and education.

This project aims to build an open and scalable data infrastructure
framework for working with, discovering, and managing data that follows
FAIR and open science principles. This is a *software* project that
focuses on working with data, but not on data itself. A description of
the project (called Seedcase) can be found at
<https://seedcase-project.org/>. The Seedcase Project will be
contributing to the research of SDCA
(<https://www.stenoaarhus.dk/research/>) as well as to that of other
Steno centers and research initiatives throughout Denmark.

Since SDCA was started only a few years ago, its technical and social
infrastructure are still being actively developed. As a result, all SDCA
personnel, including this current position and the rest of the Seedcase
team, have a direct and impactful influence on how the culture and
infrastructure is built and developed. Aside from working on Seedcase,
other responsibilities for the research software engineer, as well as
the rest of the team, include contributing to building this organization
and culture.

## Your job responsibilities

As the research software engineer, you will be:

-   Building and developing Django apps, Python Packages, and APIs in
    general for Seedcase

-   Building and developing the frontend with HTML, CSS, and potentially
    JavaScript

-   Contributing to the development of the backend database structure
    (in PostgreSQL)

-   Reviewing contributed code and documentation text

-   Assisting with or developing tools for improving analysis and
    workflow pipelines related to using Seedcase (e.g. making Python/R
    packages and scripts)

### Team-wide responsibilities

The **primary** responsibility for all members of the Seedcase team will
be building and developing the Seedcase Project. For a general overview
of overall roadmap for sub-projects and milestones see the page
<https://seedcase-project.org/community/roadmap>. More specifically,
tasks will include:

-   Refining, critiquing, and improving on the descriptions of the
    use-cases and the design and architecture of Seedcase software
    products

-   Finding and reviewing similar projects to identify what to use and
    what can be improved upon

-   Building, internally testing, developing, and deploying each
    component of Seedcase into Minimally Valuable Products, followed by
    early external testing and refining

-   Writing public-facing, *beginner-friendly*, and accessible
    documentation on contributing to and using Seedcase

-   Creating and maintaining websites connected to Seedcase
    (e.g. through GitHub Pages)

All team members' *secondary* responsibilities (dependent on time
available outside of the Seedcase Project):

-   Contributing to tasks and projects related to the general
    administration or building up of the general research environment
    (e.g. writing and/or updating onboarding documentation)

-   Assisting with building up general capacity and skills in
    reproducibility/transparency of research data analyses

-   Creating and running training sessions related to the Seedcase
    Project and to general computational analysis skills

*Note*, while the team as a whole will need to complete these tasks, any
individual member of the team *does not* need to do all these tasks and
instead will be assigned specific sections of the project.

You will report to the Unit Head Annelli Sandbæk and to the team leader
Luke Johnston.

## Your competencies

We expect, at a minimum, that you:

-   Are proficient in communicating (written and oral) in English

-   Are motivated, interested, and comfortable with working in an
    environment where many software development workflows and processes
    are still new and still need further development and refinement, as
    well as contributing on a project that is still early in the stages
    of development and that requires a diverse set of skills, knowledge,
    and tasks

-   Have demonstrated knowledge of and experience in using either
    Python, JavaScript, or R for general programming tasks (need to be
    open to learning them)

-   Have used Git or other version control software on a fairly regular
    basis for projects

-   Have knowledge or experience in developing user-facing content, such
    as websites, through HTML and CSS.

And we prefer, but don't require, that you:

-   Have developed or contributed to software packages in Python or R
    that abides by community-accepted standard practices (e.g. PIP or
    CRAN)

-   Have worked on, started, or contributed to open source projects on
    open sharing and collaborative platforms (e.g. GitHub, GitLab)

-   Have knowledge of and familiarity with *general* software
    development practices

-   Are interested in or motivated to be involved in aspects of building
    up and developing the culture and infrastructure of a newer
    organization and team

-   Have knowledge of and experience in implementing and adhering to
    FAIR/open principles

-   Are familiar with general User Interface (UI) and/or User Experience
    (UX) design principles

-   Have experience in or familiar with interacting with and/or
    developing APIs

-   Are familiar with general data engineering practices

-   Have some experience or familiarity with the research environment
    and its specific set of needs

## Who we are/will be

We currently have a core team of one full-time research software
engineers, a data manager, a database administrator, a team leader, as
well as affiliate researchers and the primary investigator. We have a
great working environment with an informal and positive atmosphere.

## What we offer

-   The position can (depending on where the applicant lives) be largely
    remote / work from home

    -   If you live or move to Aarhus for the position, we expect that
        you come into the office at SDCA at least twice a week
    -   If you live outside of Aarhus, we expect that you to participate
        in bigger in-person meetings/events (accommodation expenses can
        be covered)

-   The working hours are flexible

-   Any necessary hardware or software will be provided or covered for

-   The position allows for a lot of freedom and autonomy in work and in
    the decision making on the direction the will take

## Contact information

-   If you have any specific questions about the position, **contact**
    Annelli Sandbæk ([anesnd\@rm.dk](mailto:anesnd@rm.dk){.email})

## Formalities and salary range

-   Salary is competitive and aligns with agreements between the
    university and the national unions
